source ~/.zplug/init.zsh

export NVM_LAZY_LOAD=true
zplug "lukechilds/zsh-nvm"

zplug "modules/completion", from:prezto
zplug "modules/git", from:prezto
zplug "modules/prompt", from:prezto
zstyle ':prezto:module:prompt' theme 'sorin'

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
