#!/usr/bin/env bash

# Get the dotfiles directory's absolute path
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

# add repos
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
sudo add-apt-repository -y ppa:nathan-renniewaldock/flux
sudo add-apt-repository -y ppa:indicator-multiload/stable-daily

# update repo
sudo apt-get -y --force-yes update

# udpate existing packages
#sudo apt-get -y --force-yes upgrade

# install new packages through `apt-get`
sudo apt-get -y install \
  sublime-text-installer \
  google-chrome-beta \
  git \
  unity-tweak-tool \
  fluxgui \
  indicator-multiload \
  zsh \
  unrar

# gsettings
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2

# set `zsh` as default shell
chsh -s /bin/zsh

# symlink zplug
ln -s $SCRIPT_DIR/zplug $DOTFILES_DIR/.zplug

# symlink zshrc
ln -s $SCRIPT_DIR/shell/zshrc $DOTFILES_DIR/.zshrc

#symlink gitconfig
ln -s $SCRIPT_DIR/git/gitconfig $DOTFILES_DIR/.gitconfig